name: dirac-env  
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - torch==2.1.0 --extra-index-url https://download.pytorch.org/whl/cu118
      - absl-py==2.1.0
      - access==1.1.9
      - adjustText==1.1.1
      - affine==2.4.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alabaster==0.7.16
      - anndata==0.10.6
      - annoy==1.17.3
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array_api_compat==1.6
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - Babel==2.14.0
      - bamnostic==1.1.10
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blosc2==2.5.1
      - bokeh==2.3.1
      - boto3==1.34.63
      - botocore==1.34.63
      - branca==0.7.1
      - cachetools==5.3.2
      - certifi==2023.11.17
      - cfgv==3.4.0
      - charset-normalizer==3.3.2
      - chex==0.1.86
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.0.0
      - colorcet==3.0.1
      - comm==0.2.1
      - commonmark==0.9.1
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - csbdeep==0.7.4
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cykhash==2.0.1
      - Cython==3.0.8
      - debugpy==1.8.1
      - decorator==5.1.1
      - decoupler==1.6.0
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - descartes==1.1.0
      - dill==0.3.7
      - distlib==0.3.8
      - docrep==0.3.2
      - docutils==0.21.2
      - dunamai==1.19.1
      - dynamo-release==1.4.0
      - easydict==1.13
      - episcanpy==0.4.0
      - equinox==0.11.3
      - esda==2.5.1
      - et-xmlfile==1.1.0
      - etils==1.5.2
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fastremap==1.14.1
      - fbgbp==0.2.1
      - fbpca==1.0
      - filelock==3.13.1
      - fiona==1.9.5
      - flatbuffers==24.3.25
      - flax==0.8.3
      - flit==3.9.0
      - flit_core==3.9.0
      - folium==0.15.1
      - fonttools==4.47.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - gast==0.5.4
      - geopandas==0.14.3
      - geosketch==1.2
      - get-annotations==0.1.2
      - get_version==3.5.5
      - giddy==2.3.5
      - google-auth==2.28.0
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - grpcio==1.60.1
      - h11==0.14.0
      - h5py==3.11.0
      - hmmlearn==0.3.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - identify==2.5.34
      - idna==3.6
      - igraph==0.10.4
      - imagecodecs==2024.6.1
      - imageio==2.33.1
      - imagesize==1.4.1
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - inequality==1.0.0
      - intervaltree==2.1.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jax==0.4.25
      - jaxlib==0.4.25
      - jaxopt==0.8.3
      - jaxtyping==0.2.28
      - jedi==0.19.1
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kaleido==0.2.1
      - KDEpy==1.1.8
      - kiwisolver==1.4.5
      - kneed==0.8.5
      - kornia==0.7.1
      - lazy_loader==0.3
      - legacy-api-wrap==1.4
      - leidenalg==0.9.1
      - libclang==16.0.6
      - libpysal==4.8.1
      - lightning==2.1.4
      - lightning-utilities==0.11.2
      - lineax==0.0.4
      - llvmlite==0.41.1
      - logging-release==0.0.4
      - loguru==0.7.2
      - loompy==3.0.7
      - louvain==0.8.0
      - MACS3==3.0.0
      - mapclassify==2.6.1
      - Markdown==3.5.2
      - markdown-it-py==3.0.0
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mgwr==2.2.1
      - mistune==3.0.2
      - mizani==0.9.3
      - ml-collections==0.1.1
      - ml-dtypes==0.4.0
      - momepy==0.6.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - mudata==0.2.3
      - multidict==6.0.5
      - multipledispatch==1.0.0
      - multiprocess==0.70.15
      - mypy-extensions==1.0.0
      - natsort==8.5.2
      - nbclassic==1.1.6
      - nbclient==0.9.3
      - nbconvert==7.8.0
      - nbformat==5.9.2
      - nest-asyncio==1.5.7
      - networkx==2.11.1
      - notebook==7.1.7
      - notebook_shim==0.2.3
      - numba==0.58.1
      - numexpr==2.8.6
      - numpy==1.26.2
