[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "DIRAC"
authors = [{name = "XU CHANG", email = "xuchang0214@163.com"}]
dynamic = ["version", "description"]
